function macros() {
#macro RIGHT 0
#macro UP 1
#macro LEFT 2
#macro DOWN 3
#macro DASH_COST 5
#macro ATTACK_COST 2
#macro REVOLVER 1
#macro SHOTGUN 2
#macro BAZOOKA 3
#macro GRENADE_LAUNCHER 4
#macro STICKY_GRENADE_LAUNCHER 5
#macro CROSSBOW 6
#macro TRIPLE_MACHINE_GUN 7
#macro TOXIC_BOW 8
#macro STATE_MOVE 0
#macro STATE_ATTACK 1
#macro STATE_CHASE 2
#macro STATE_SECUNDARIES 3
#macro STATE_DOOR 4
#macro STATE_FALLING 5
#macro STATE_DASH 6
#macro STATE_ATTACK_HEAVY 7
#macro STATE_IDLE 8
#macro STATE_CHARGE 9
#macro STATE_WANDER 10
#macro STATE_STALL 11
#macro WEP_NAME 9
#macro WEP_TYPE 7
#macro WEP_AUTO 6
#macro WEP_LOAD 5
#macro WEP_COST 4
#macro WEP_SWAP 3
#macro WEP_AREA 2
#macro WEP_TEXT 1
#macro WEP_SPRITE 0
#macro NAME 2
#macro TYP_NAME 2
#macro AMMO 1
#macro AMAX 0
#macro MELEE 0
#macro BULLETS 1
#macro SHELLS 2
#macro BOLTS 3
#macro EXPLOSIVES 4
#macro ENERGY 5
#macro NOTHING 0
#macro DEFECTABLE 1
#macro DESTRUCTABLE 2
#macro MENU_START 0
#macro MENU_STANDARD 1
#macro MENU_SETTINGS 2
#macro MENU_NEW_GAME 3
#macro KEYBOARD 2
#macro GAMEPAD_1 0
#macro GAMEPAD_2 1
#macro ENEMY 1



}
